### ISSUE TITLE
Can this nSimulations be set by default in your forecast method? Or can you use the `nsim` option that is used by other models? Having the same option names is critical so we can have interoperability of the same code between models.

### ISSUE THREAD

**Issue by nickreich** [reichlab/german-flu-forecasting#7]
@katehoffshutta Can this nSimulations be set by default in your forecast method? Or can you use the `nsim` option that is used by other models? Having the same option names is critical so we can have interoperability of the same code between models.

_Originally posted by @nickreich in https://github.com/reichlab/german-flu-forecasting/pull/4/review_comment/create_

**Comment by katehoffshutta** [comment]
Sure, both of those.  Is there a default that's being used?

**Comment by nickreich** [comment]
Best would be to use the existing `nsim` option and set it to default to something reasonable for your particular model. E.g. sarimaTDModel uses `nsim=1000`:
https://github.com/reichlab/german-flu-forecasting/blob/b716300c1281e2b86a31cf810fe0244605bea6b8/models/sarimaTDModel.R#L21

**Comment by katehoffshutta** [comment]
Great - thanks.  I'll set it to 1000, with the caveat that it will probably be slow if you want to forecast the whole season.  It takes about 2 min per season-week to do 1000 simulations with a prior of size 10,000 curves, which seems to be a good default.

**Comment by nickreich** [comment]
Sounds good. That doesn't sound too bad in terms of speed. I'm running it now on the training year with the model default specifications.
